name: ReIMAGINELIFE
favicon: null
layout_spectrum: 0.36489
typography_spectrum: 0.73073
title: R3IMAGINE LIFE
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#1d1e23'
    - '#4a5478'
    - '#8e9dc8'
    - '#dcdfce'
    - '#dd0023'
  brandStrength: 0.75
  lightness: 0.1875
  saturation: 0.875
  rhythmicContrast: 0.25
purpose: []
