name: ReIMAGINELIFE
favicon: null
layout_spectrum: 0.4282586320769042
typography_spectrum: 0.5033386391587555
title: R3IMAGINE LIFE
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#A690A4'
    - '#B68F9D'
    - '#C8ACAB'
    - '#FBB9BF'
    - '#E376B7'
  brandStrength: 0.4030065559782088
  lightness: 0.15710495598614216
  saturation: 0.8827657839283347
  rhythmicContrast: 0.5613144037779421
purpose: []
